
import Header from '@/components/Header/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer/Footer'
import CabinetHeader from '@/components/CabinetHeader/CabinetHeader'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {
  if(children.props.childProp.segment !== "cabinet") {
    return (
      <html lang="en">
        <body className={inter.className + " " + "min-h-screen flex flex-col bg-gradient-to-t from-slate-100 to-white text-black"}>
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    )
  } else {
    return (
      <html lang="en">
        <body className={inter.className + " " + "min-h-screen flex flex-col bg-gradient-to-t from-slate-100 to-white text-black"}>
          <CabinetHeader />
          {children}
        </body>
      </html>
    )
  }
  
}
